# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

acougue = Category.create(name: 'Açougue')
laticinios = Category.create(name: 'Laticínios')
higiene = Category.create(name: 'Higiene')
limpeza = Category.create(name: 'Limpeza')
hortifruti = Category.create(name: 'Hortifrutigranjeiros')
frios = Category.create(name: 'Frios')
pet = Category.create(name: 'Pet')
ferragem = Category.create(name: 'Ferragem')
massas = Category.create(name: 'Massas')
graos = Category.create(name: 'Grãos, Cereais e Farináceos')
matinais = Category.create(name: 'Matinais')
festas = Category.create(name: 'Festas')
paes = Category.create(name: 'Pães')
biscoitos = Category.create(name: 'Biscoitos')
sobremesas = Category.create(name: 'Sobremesas')
conservas = Category.create(name: 'Conservas')
bebidas = Category.create(name: 'Bebidas')
jardim = Category.create(name: 'Jardim')
piscina = Category.create(name: 'Piscina')
oleos = Category.create(name: 'Óleos e Temperos')
peixes = Category.create(name: 'Peixes')
congelados = Category.create(name: 'Congelados')
Item.create(name: 'Carne Moída', category_id: acougue.id)
Item.create(name: 'Alcatra Bovina', category_id: acougue.id)
Item.create(name: 'Alcatra Suína', category_id: acougue.id)
Item.create(name: 'Costela Suína', category_id: acougue.id)
Item.create(name: 'Costela Bovina', category_id: acougue.id)
Item.create(name: 'Cupim', category_id: acougue.id)
Item.create(name: 'Maminha', category_id: acougue.id)
Item.create(name: 'Músculo', category_id: acougue.id)
Item.create(name: 'Picanha Bovina', category_id: acougue.id)
Item.create(name: 'Picanha Suína', category_id: acougue.id)
Item.create(name: 'Filé Bovino', category_id: acougue.id)
Item.create(name: 'Filé Suíno', category_id: acougue.id)
Item.create(name: 'Peito de Frango', category_id: acougue.id)
Item.create(name: 'Filezinho de Peito de Frango', category_id: acougue.id)
Item.create(name: 'Coração de Frango', category_id: acougue.id)
Item.create(name: 'Coxa de Frango', category_id: acougue.id)
Item.create(name: 'Sobrecoxa de Frango', category_id: acougue.id)
Item.create(name: 'Asa de Frango', category_id: acougue.id)
Item.create(name: 'Salsicha', category_id: acougue.id)
Item.create(name: 'Linguiça', category_id: acougue.id)
Item.create(name: 'Carvão', category_id: acougue.id)
Item.create(name: 'Espeto Simples', category_id: acougue.id)
Item.create(name: 'Espeto Duplo', category_id: acougue.id)
Item.create(name: 'Grelha', category_id: acougue.id)
Item.create(name: 'Churrasqueira Portátil', category_id: acougue.id)
Item.create(name: 'Espetinho', category_id: acougue.id)
Item.create(name: 'Lombinho Suíno', category_id: acougue.id)
Item.create(name: 'Bacon', category_id: acougue.id)
Item.create(name: 'Água sem Gás', category_id: bebidas.id)
Item.create(name: 'Água com Gás', category_id: bebidas.id)
Item.create(name: 'Cerveja', category_id: bebidas.id)
Item.create(name: 'Refrigerante', category_id: bebidas.id)
Item.create(name: 'Vinho', category_id: bebidas.id)
Item.create(name: 'Suco', category_id: bebidas.id)
Item.create(name: 'Cachaça', category_id: bebidas.id)
Item.create(name: 'Vodka', category_id: bebidas.id)
Item.create(name: 'Whiskey', category_id: bebidas.id)
Item.create(name: 'Espumante', category_id: bebidas.id)
Item.create(name: 'Arroz', category_id: graos.id)
Item.create(name: 'Feijão', category_id: graos.id)
Item.create(name: 'Lentilha', category_id: graos.id)
Item.create(name: 'Aveia', category_id: graos.id)
Item.create(name: 'Farinha de Mandioca', category_id: graos.id)
Item.create(name: 'Farinha de Trigo', category_id: graos.id)
Item.create(name: 'Farinha de Rosca', category_id: graos.id)
Item.create(name: 'Mistura para Bolo', category_id: graos.id)
Item.create(name: 'Farinha de Cuscuz', category_id: graos.id)
Item.create(name: 'Grão de Bico', category_id: graos.id)
Item.create(name: 'Canjica', category_id: graos.id)
Item.create(name: 'Pipoca', category_id: graos.id)
Item.create(name: 'Maçã', category_id: hortifruti.id)
Item.create(name: 'Uva', category_id: hortifruti.id)
Item.create(name: 'Pera', category_id: hortifruti.id)
Item.create(name: 'Banana', category_id: hortifruti.id)
Item.create(name: 'Abacaxi', category_id: hortifruti.id)
Item.create(name: 'Abacate', category_id: hortifruti.id)
Item.create(name: 'Acerola', category_id: hortifruti.id)
Item.create(name: 'Mamão', category_id: hortifruti.id)
Item.create(name: 'Melão', category_id: hortifruti.id)
Item.create(name: 'Melancia', category_id: hortifruti.id)
Item.create(name: 'Laranja', category_id: hortifruti.id)
Item.create(name: 'Tangerina', category_id: hortifruti.id)
Item.create(name: 'Limão', category_id: hortifruti.id)
Item.create(name: 'Alface', category_id: hortifruti.id)
Item.create(name: 'Rúcula', category_id: hortifruti.id)
Item.create(name: 'Agrião', category_id: hortifruti.id)
Item.create(name: 'Espinafre', category_id: hortifruti.id)
Item.create(name: 'Couve', category_id: hortifruti.id)
Item.create(name: 'Maracujá', category_id: hortifruti.id)
Item.create(name: 'Tomate', category_id: hortifruti.id)
Item.create(name: 'Pimentão', category_id: hortifruti.id)
Item.create(name: 'Pimenta', category_id: hortifruti.id)
Item.create(name: 'Cebola', category_id: hortifruti.id)
Item.create(name: 'Alho', category_id: hortifruti.id)
Item.create(name: 'Cenoura', category_id: hortifruti.id)
Item.create(name: 'Beterraba', category_id: hortifruti.id)
Item.create(name: 'Chuchu', category_id: hortifruti.id)
Item.create(name: 'Salsinha', category_id: hortifruti.id)
Item.create(name: 'Coentro', category_id: hortifruti.id)
Item.create(name: 'Cebolinha', category_id: hortifruti.id)
Item.create(name: 'Manjericão', category_id: hortifruti.id)
Item.create(name: 'Hortelã', category_id: hortifruti.id)
Item.create(name: 'Pepino', category_id: hortifruti.id)
Item.create(name: 'Brócolis', category_id: hortifruti.id)
Item.create(name: 'Couve-Flor', category_id: hortifruti.id)
Item.create(name: 'Batata', category_id: hortifruti.id)
Item.create(name: 'Batata Doce', category_id: hortifruti.id)
Item.create(name: 'Aipim', category_id: hortifruti.id)
Item.create(name: 'Abóbora', category_id: hortifruti.id)
Item.create(name: 'Abobrinha', category_id: hortifruti.id)
Item.create(name: 'Berinjela', category_id: hortifruti.id)
Item.create(name: 'Ovos', category_id: hortifruti.id)
Item.create(name: 'Coco', category_id: hortifruti.id)
Item.create(name: 'Morango', category_id: hortifruti.id)
Item.create(name: 'Espiga de Milho', category_id: hortifruti.id)
Item.create(name: 'Manga', category_id: hortifruti.id)
Item.create(name: 'Azeitonas', category_id: conservas.id)
Item.create(name: 'Champgnon', category_id: conservas.id)
Item.create(name: 'Pepino em Conserva', category_id: conservas.id)
Item.create(name: 'Milho Verde', category_id: conservas.id)
Item.create(name: 'Ervilha', category_id: conservas.id)
Item.create(name: 'Seleta de Legumes', category_id: conservas.id)
Item.create(name: 'Palmito', category_id: conservas.id)
Item.create(name: 'Atum em lata', category_id: conservas.id)
Item.create(name: 'Sardinha em lata', category_id: conservas.id)
Item.create(name: 'Queijo Prato', category_id: frios.id)
Item.create(name: 'Presunto', category_id: frios.id)
Item.create(name: 'Apresuntado', category_id: frios.id)
Item.create(name: 'Mortadela', category_id: frios.id)
Item.create(name: 'Peito de Peru', category_id: frios.id)
Item.create(name: 'Salame', category_id: frios.id)
Item.create(name: 'Queijo Provolone', category_id: frios.id)
Item.create(name: 'Queijo Muzzarella', category_id: frios.id)
Item.create(name: 'Queijo Gorgonzola', category_id: frios.id)
Item.create(name: 'Leite', category_id: laticinios.id)
Item.create(name: 'Leite em Pó', category_id: laticinios.id)
Item.create(name: 'Iogurte', category_id: laticinios.id)
Item.create(name: 'Requeijão', category_id: laticinios.id)
Item.create(name: 'Manteiga', category_id: laticinios.id)
Item.create(name: 'Margarina', category_id: laticinios.id)
Item.create(name: 'Leite Fermentado', category_id: laticinios.id)
Item.create(name: 'Achocolatado para Beber', category_id: laticinios.id)
Item.create(name: 'Pudim', category_id: laticinios.id)
Item.create(name: 'Desodorante', category_id: higiene.id)
Item.create(name: 'Shampoo', category_id: higiene.id)
Item.create(name: 'Shampoo Infantil', category_id: higiene.id)
Item.create(name: 'Condicionador', category_id: higiene.id)
Item.create(name: 'Sabonete', category_id: higiene.id)
Item.create(name: 'Sabonete Infantil', category_id: higiene.id)
Item.create(name: 'Esponja para banho', category_id: higiene.id)
Item.create(name: 'Lenço de papel', category_id: higiene.id)
Item.create(name: 'Lenço Umidecido', category_id: higiene.id)
Item.create(name: 'Papel Higiênico', category_id: higiene.id)
Item.create(name: 'Guardanapo', category_id: higiene.id)
Item.create(name: 'Papel Absorvente', category_id: higiene.id)
Item.create(name: 'Creme Dental', category_id: higiene.id)
Item.create(name: 'Creme Dental Infantil', category_id: higiene.id)
Item.create(name: 'Escova de Dentes', category_id: higiene.id)
Item.create(name: 'Escova de Cabelos', category_id: higiene.id)
Item.create(name: 'Pente', category_id: higiene.id)
Item.create(name: 'Gel de Cabelos', category_id: higiene.id)
Item.create(name: 'Hidratante', category_id: higiene.id)
Item.create(name: 'Protetor Solar', category_id: higiene.id)
Item.create(name: 'Fralda Infantil', category_id: higiene.id)
Item.create(name: 'Fralda Geriátrica', category_id: higiene.id)
Item.create(name: 'Creme de Barbear', category_id: higiene.id)
Item.create(name: 'Loção Pós-Barba', category_id: higiene.id)
Item.create(name: 'Aparelho de Barbear', category_id: higiene.id)
Item.create(name: 'Lâmina de Barbear', category_id: higiene.id)
Item.create(name: 'Cera', category_id: higiene.id)
Item.create(name: 'Absorvente', category_id: higiene.id)
Item.create(name: 'Pomada para Assaduras', category_id: higiene.id)
Item.create(name: 'Haste Flexível', category_id: higiene.id)
Item.create(name: 'Algodão', category_id: higiene.id)
Item.create(name: 'Preservativo', category_id: higiene.id)
Item.create(name: 'Amaciante', category_id: limpeza.id)
Item.create(name: 'Sabão em Pó', category_id: limpeza.id)
Item.create(name: 'Sabão em Barra', category_id: limpeza.id)
Item.create(name: 'Sabão Líquido', category_id: limpeza.id)
Item.create(name: 'Tira Manchas', category_id: limpeza.id)
Item.create(name: 'Água Sanitária', category_id: limpeza.id)
Item.create(name: 'Desifentante', category_id: limpeza.id)
Item.create(name: 'Vassoura', category_id: limpeza.id)
Item.create(name: 'Saco de Lixo', category_id: limpeza.id)
Item.create(name: 'Balde', category_id: limpeza.id)
Item.create(name: 'Palha de aço', category_id: limpeza.id)
Item.create(name: 'Detergente', category_id: limpeza.id)
Item.create(name: 'Esponja', category_id: limpeza.id)
Item.create(name: 'Desengordurante', category_id: limpeza.id)
Item.create(name: 'Bacia', category_id: limpeza.id)
Item.create(name: 'Sardinha', category_id: peixes.id)
Item.create(name: 'Camarão', category_id: peixes.id)
Item.create(name: 'Tainha', category_id: peixes.id)
Item.create(name: 'Salmão', category_id: peixes.id)
Item.create(name: 'Bacalhau', category_id: peixes.id)
Item.create(name: 'Marisco', category_id: peixes.id)
Item.create(name: 'Corvina', category_id: peixes.id)
Item.create(name: 'Pescada Amarela', category_id: peixes.id)
Item.create(name: 'Linguado', category_id: peixes.id)
Item.create(name: 'Ração de Cachorro', category_id: pet.id)
Item.create(name: 'Ração de Gato', category_id: pet.id)
Item.create(name: 'Alpiste', category_id: pet.id)
Item.create(name: 'Areia para Gato', category_id: pet.id)
Item.create(name: 'Shampoo Pet', category_id: pet.id)
Item.create(name: 'Coleira', category_id: pet.id)
Item.create(name: 'Pote de Ração', category_id: pet.id)
Item.create(name: 'Cama para Pet', category_id: pet.id)
Item.create(name: 'Brinquedo para Pet', category_id: pet.id)
Item.create(name: 'Kit Ferramentas', category_id: ferragem.id)
Item.create(name: 'Fita Dupla Face', category_id: ferragem.id)
Item.create(name: 'Cola Epoxi', category_id: ferragem.id)
Item.create(name: 'Cola Bonder', category_id: ferragem.id)
Item.create(name: 'Lâmpada', category_id: ferragem.id)
Item.create(name: 'Extensão Elétrica', category_id: ferragem.id)
Item.create(name: 'Chave de Roda', category_id: ferragem.id)
Item.create(name: 'Chave de Fenda', category_id: ferragem.id)
Item.create(name: 'Chave de Phillips', category_id: ferragem.id)
Item.create(name: 'Benjamin(T) de Tomada', category_id: ferragem.id)
Item.create(name: 'Adaptador de Tomada', category_id: ferragem.id)
Item.create(name: 'Resistência de Chuveiro', category_id: ferragem.id)
Item.create(name: 'Espagueti', category_id: massas.id)
Item.create(name: 'Talharim', category_id: massas.id)
Item.create(name: 'Penne', category_id: massas.id)
Item.create(name: 'Massa Parafuso', category_id: massas.id)
Item.create(name: 'Queijo Ralado', category_id: massas.id)
Item.create(name: 'Massa de Lasanha', category_id: massas.id)
Item.create(name: 'Macarrão Instantâneo', category_id: massas.id)
Item.create(name: 'Molho de Tomate', category_id: massas.id)
Item.create(name: 'Extrato de Tomate', category_id: massas.id)
Item.create(name: 'Molho Branco', category_id: massas.id)
Item.create(name: 'Macarrão de Sopa', category_id: massas.id)
Item.create(name: 'Sopa Intantânea', category_id: massas.id)
Item.create(name: 'Café', category_id: matinais.id)
Item.create(name: 'Café Solúvel', category_id: matinais.id)
Item.create(name: 'Chocolate em Pó', category_id: matinais.id)
Item.create(name: 'Geléia', category_id: matinais.id)
Item.create(name: 'Flocos de Milho Cereal', category_id: matinais.id)
Item.create(name: 'Filtro de Café', category_id: matinais.id)
Item.create(name: 'Coador de Café', category_id: matinais.id)
Item.create(name: 'Cápsula de Café', category_id: matinais.id)
Item.create(name: 'Chá', category_id: matinais.id)
Item.create(name: 'Erva Mate', category_id: matinais.id)
Item.create(name: 'Cuia', category_id: matinais.id)
Item.create(name: 'Bomba de Chimarrão', category_id: matinais.id)
Item.create(name: 'Filtro de Bomba', category_id: matinais.id)
Item.create(name: 'Copo Plástico', category_id: festas.id)
Item.create(name: 'Prato Plástico', category_id: festas.id)
Item.create(name: 'Colher Plástico', category_id: festas.id)
Item.create(name: 'Garfo Plástico', category_id: festas.id)
Item.create(name: 'Faca Plástica', category_id: festas.id)
Item.create(name: 'Vela de Aniversário', category_id: festas.id)
Item.create(name: 'Chapéu de Aniversário', category_id: festas.id)
Item.create(name: 'Kit Decoração de Aniversário', category_id: festas.id)
Item.create(name: 'Pão Francês', category_id: paes.id)
Item.create(name: 'Baguete', category_id: paes.id)
Item.create(name: 'Pão de Forma', category_id: paes.id)
Item.create(name: 'Sonho', category_id: paes.id)
Item.create(name: 'Croissant', category_id: paes.id)
Item.create(name: 'Pão de Hot Dog', category_id: paes.id)
Item.create(name: 'Torradinha', category_id: paes.id)
Item.create(name: 'Pão de Queijo', category_id: paes.id)
Item.create(name: 'Biscoito Recheado', category_id: biscoitos.id)
Item.create(name: 'Biscoito Água e Sal', category_id: biscoitos.id)
Item.create(name: 'Biscoito Cream Cracker', category_id: biscoitos.id)
Item.create(name: 'Biscoito Wafle', category_id: biscoitos.id)
Item.create(name: 'Cookie', category_id: biscoitos.id)
Item.create(name: 'Biscoito Amanteigado', category_id: biscoitos.id)
Item.create(name: 'Bolacha Maria', category_id: biscoitos.id)
Item.create(name: 'Bolacha Champagne', category_id: biscoitos.id)
Item.create(name: 'Leite Condensado', category_id: sobremesas.id)
Item.create(name: 'Creme de Leite', category_id: sobremesas.id)
Item.create(name: 'Doce de Leite', category_id: sobremesas.id)
Item.create(name: 'Açúcar', category_id: sobremesas.id)
Item.create(name: 'Açúcar Confeiteiro', category_id: sobremesas.id)
Item.create(name: 'Chocolate ao Leite', category_id: sobremesas.id)
Item.create(name: 'Chocolate Amargo', category_id: sobremesas.id)
Item.create(name: 'Chocolate Branco', category_id: sobremesas.id)
Item.create(name: 'Gotas de Chocolate', category_id: sobremesas.id)
Item.create(name: 'Chocolate Granulado', category_id: sobremesas.id)
Item.create(name: 'Mistura de Bolo', category_id: sobremesas.id)
Item.create(name: 'Coco Ralado', category_id: sobremesas.id)
Item.create(name: 'Leite de Coco', category_id: sobremesas.id)
Item.create(name: 'Mangueira', category_id: jardim.id)
Item.create(name: 'Vaso de Planta', category_id: jardim.id)
Item.create(name: 'Adubo', category_id: jardim.id)
Item.create(name: 'Terra', category_id: jardim.id)
Item.create(name: 'Pá de Jardim', category_id: jardim.id)
Item.create(name: 'Ponta de Mangueira', category_id: jardim.id)
Item.create(name: 'Semente', category_id: jardim.id)
Item.create(name: 'Boia', category_id: piscina.id)
Item.create(name: 'Piscina de Plástico', category_id: piscina.id)
Item.create(name: 'Chinelo de Dedo', category_id: piscina.id)
Item.create(name: 'Caixa Térmica', category_id: piscina.id)
Item.create(name: 'Cadeira de Praia', category_id: piscina.id)
Item.create(name: 'Cadeira de Plástico', category_id: piscina.id)
Item.create(name: 'Mesa de Plástico', category_id: piscina.id)
Item.create(name: 'Cloro', category_id: piscina.id)
Item.create(name: 'Bolsa Térmica', category_id: piscina.id)
Item.create(name: 'Guarda-sol', category_id: piscina.id)
Item.create(name: 'Esteira de Praia', category_id: piscina.id)
Item.create(name: 'Óleo de Soja', category_id: oleos.id)
Item.create(name: 'Óleo de Milho', category_id: oleos.id)
Item.create(name: 'Óleo de Girassol', category_id: oleos.id)
Item.create(name: 'Óleo de Canola', category_id: oleos.id)
Item.create(name: 'Óleo de Algodão', category_id: oleos.id)
Item.create(name: 'Azeite de Oliva', category_id: oleos.id)
Item.create(name: 'Azeite de Oliva Extra Virgem', category_id: oleos.id)
Item.create(name: 'Vinagre', category_id: oleos.id)
Item.create(name: 'Aceto Balsâmico', category_id: oleos.id)
Item.create(name: 'Azeite de Dendê', category_id: oleos.id)
Item.create(name: 'Óleo de Coco', category_id: oleos.id)
Item.create(name: 'Caldo de Galinha', category_id: oleos.id)
Item.create(name: 'Caldo de Carne', category_id: oleos.id)
Item.create(name: 'Caldo de Legumes', category_id: oleos.id)
Item.create(name: 'Tempero de Arroz', category_id: oleos.id)
Item.create(name: 'Tempero de Feijão', category_id: oleos.id)
Item.create(name: 'Tempero Completo', category_id: oleos.id)
Item.create(name: 'Sal', category_id: oleos.id)
Item.create(name: 'Sal Grosso', category_id: oleos.id)
Item.create(name: 'Orégano', category_id: oleos.id)
Item.create(name: 'Sálvia', category_id: oleos.id)
Item.create(name: 'Alecrim', category_id: oleos.id)
Item.create(name: 'Salsa Desidratada', category_id: oleos.id)
Item.create(name: 'Manjericão Desidratado', category_id: oleos.id)
Item.create(name: 'Pimenta do Reino', category_id: oleos.id)
Item.create(name: 'Molho de Pimenta', category_id: oleos.id)
Item.create(name: 'Cominho', category_id: oleos.id)
Item.create(name: 'Noz Moscada', category_id: oleos.id)
Item.create(name: 'Canela', category_id: oleos.id)
Item.create(name: 'Cravo', category_id: oleos.id)
Item.create(name: 'Bicarbonato de Sódio', category_id: oleos.id)
Item.create(name: 'Pizza', category_id: congelados.id)
Item.create(name: 'Lasanha', category_id: congelados.id)
Item.create(name: 'Nuggets', category_id: congelados.id)
Item.create(name: 'Kibe', category_id: congelados.id)
Item.create(name: 'Coxinha', category_id: congelados.id)
Item.create(name: 'Empanados', category_id: congelados.id)
Item.create(name: 'Ravioli', category_id: congelados.id)
Item.create(name: 'Capeleti', category_id: congelados.id)
Item.create(name: 'Sorvete', category_id: congelados.id)
Item.create(name: 'Picolé', category_id: congelados.id)
Item.create(name: 'Polpa de Fruta', category_id: congelados.id)
Item.create(name: 'Hamburger', category_id: congelados.id)
Item.create(name: 'Batata Frita', category_id: congelados.id)
